//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAMShop.category {
    
    
    public partial class category {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new UAMShop.MasterPages.CategoryTemplate Master {
            get {
                return ((UAMShop.MasterPages.CategoryTemplate)(base.Master));
            }
        }
    }
}
